GCC std::optional whack-a-mole [1/N]: QTypedJson::Reader
This is a patch in a series (of as of yet unknown length) to fix GCC's
-Werror={maybe-,}uninitialized relating to std::optional use.

In this case, using optional::emplace() instead of
optional::operator=(optional(T)) fixes a ton of these kinds of
warnings-as-errors:

  In constructor ‘QArrayDataPointer<T>::QArrayDataPointer(QArrayDataPointer<T>&&) [with T = QJsonValue]’,
    inlined from ‘QArrayDataPointer<T>& QArrayDataPointer<T>::operator=(QArrayDataPointer<T>&&) [with T = QJsonValue]’ at qtbase/src/corelib/tools/qarraydatapointer.h:69:5,
    inlined from ‘QList<QJsonValue>& QList<QJsonValue>::operator=(QList<QJsonValue>&&)’ at qtbase/src/corelib/tools/qlist.h:68:7,
    inlined from ‘constexpr void std::_Optional_payload_base<_Tp>::_M_move_assign(std::_Optional_payload_base<_Tp>&&) [with _Tp = QList<QJsonValue>]’ at /d/gcc/12/include/c++/12.1.1/optional:194:19,
    inlined from ‘constexpr std::_Optional_payload<_Tp, true, false, false>& std::_Optional_payload<_Tp, true, false, false>::operator=(std::_Optional_payload<_Tp, true, false, false>&&) [with _Tp = QLis
t<QJsonValue>]’ at /d/gcc/12/include/c++/12.1.1/optional:420:22,
    inlined from ‘constexpr std::_Optional_payload<_Tp, false, _Copy, _Move>& std::_Optional_payload<_Tp, false, _Copy, _Move>::operator=(std::_Optional_payload<_Tp, false, _Copy, _Move>&&) [with _Tp = Q
List<QJsonValue>; bool _Copy = false; bool _Move = false]’ at /d/gcc/12/include/c++/12.1.1/optional:436:26,
    inlined from ‘constexpr std::_Optional_base<_Tp, <anonymous>, <anonymous> >& std::_Optional_base<_Tp, <anonymous>, <anonymous> >::operator=(std::_Optional_base<_Tp, <anonymous>, <anonymous> >&&) [wit
h _Tp = QList<QJsonValue>; bool <anonymous> = false; bool <anonymous> = false]’ at /d/gcc/12/include/c++/12.1.1/optional:550:23,
    inlined from ‘constexpr std::optional<QList<QJsonValue> >& std::optional<QList<QJsonValue> >::operator=(std::optional<QList<QJsonValue> >&&)’ at /d/gcc/12/include/c++/12.1.1/optional:705:11,
    inlined from ‘QLspSpecification::Command& QLspSpecification::Command::operator=(QLspSpecification::Command&&)’ at qtlanguageserver/src/languageserver/qlanguageserverspectypes_p.h:519:31,
    inlined from ‘constexpr std::enable_if_t<__and_v<std::__not_<std::is_same<std::optional<_Tp>, typename std::remove_cv<typename std::remove_reference<_Iter>::type>::type> >, std::__not_<std::__and_<std::is_scalar<_Tp>, std::is_same<_Tp, typename std::decay<_Up>::type> > >, std::is_constructible<_Tp, _Up>, std::is_assignable<_Tp&, _Up> >, std::optional<_Tp>&> std::optional<_Tp>::operator=(_Up&&) [with
 _Up = QLspSpecification::Command; _Tp = QLspSpecification::Command]’ at /d/gcc/12/include/c++/12.1.1/optional:851:21,
    inlined from ‘bool QTypedJson::Reader::handleOptional(T&) [with T = std::optional<QLspSpecification::Command>]’ at qtlanguageserver/src/jsonrpc/qtypedjson_p.h:306:16,
    inlined from ‘void QTypedJson::doWalk(W&, T&) [with W = Reader; T = std::optional<QLspSpecification::Command>]’ at qtlanguageserver/src/jsonrpc/qtypedjson_p.h:456:33,
    inlined from ‘void QTypedJson::field(W&, const C&, T&) [with W = Reader; C = char [8]; T = std::optional<QLspSpecification::Command>]’ at qtlanguageserver/src/jsonrpc/qtypedjson_p.h:419:15:
qtbase/src/corelib/tools/qarraydatapointer.h:62:19: error: ‘*(QArrayDataPointer<QJsonValue>*)((char*)&<unnamed> + offsetof(QLspSpecification::value_type, QLspSpecification::Command::arguments.std::optional<QList<QJsonValue> >::<unnamed>.std::_Optional_base<QList<QJsonValue>, false, false>::<unnamed>)).QArrayDataPointer<QJsonValue>::d’ may be used uninitialized [-Werror=maybe-uninitialized]
   62 |         : d(other.d), ptr(other.ptr), size(other.size)
      |             ~~~~~~^

Apart from fixing warnings, it's also more efficient.

Upstream bug reports:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86465
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100115
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102801
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105749

IOW: they don't seem to care much.

Task-number: QTBUG-103924
Pick-to: 6.3
Change-Id: I0a8a363c05ad87f0a60a56f60f9d2eaa3e36591a
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>